name: sunraster
channels:
  - sunpy
dependencies:
  - python
  - pip
  - openjpeg
  - graphviz!=2.42.*
  - pip:
    - sunpy>=1.0.0
    - ndcube>=1.1.0
    - extension_helpers
    - sphinx
    - sphinx-gallery
    - sqlalchemy
    - sunpy-sphinx-theme
    - towncrier
